#!/usr/bin/env sh
echo "SOURCE_BRANCH: ${SOURCE_BRANCH}"
export SOURCE_COMMIT=$(git rev-parse HEAD)
echo "SOURCE_COMMIT: ${SOURCE_COMMIT}"
export BUILD_TIME="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo "BUILD_TIME: ${BUILD_TIME}"
echo "DOCKER_REPO: ${DOCKER_REPO}"

docker build \
    --build-arg "SOURCE_BRANCH=${SOURCE_BRANCH}" \
    --build-arg "SOURCE_COMMIT=${SOURCE_COMMIT}" \
    --build-arg "BUILD_TIME=${BUILD_TIME}" \
    --build-arg "DOCKER_REPO=${DOCKER_REPO}" \
    --tag $IMAGE_NAME .
